### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by sp-ytdl-core** [koreanpanda345/Pokemon_Bot#1]
error
   at CommandoClient.<anonymous> (/home/runner/PokemonBot/node_modules/discord.js-commando/src/client.js:84:11)
    at Object.onceWrapper (events.js:421:28)
    at CommandoClient.emit (events.js:327:22)
    at WebSocketManager.triggerClientReady (/home/runner/PokemonBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (/home/runner/PokemonBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (/home/runner/PokemonBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (/home/runner/PokemonBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (/home/runner/PokemonBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (/home/runner/PokemonBot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
(node:296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by koreanpanda345** [comment]
yea, its outdated, so i am not surprised it doesn't work

**Comment by sp-ytdl-core** [comment]
please update it

**Comment by Natemo2625** [comment]
@koreanpanda345 if you want, i could try to update it

**Comment by koreanpanda345** [comment]
If you want to do so, be my guest. It was just a fun project that i wanted to do, but turned out to be added stress that i didn't want to deal with at the current moment.

**Comment by Natemo2625** [comment]
first thing i noticed is that you didn't list discord.js in package.json

**Comment by Natemo2625** [comment]
@koreanpanda345 i'm currently doing all of my hosting on repl.it so now I have to deal with quick.db not installing all of it's dependencies first time again lol

**Comment by Natemo2625** [comment]
@koreanpanda345 if you want, you could go ahead and merge my pull request #2 with my current changes. My discord is Natemo#0661 if you need me and I don't respond on GitHub.

**Comment by Natemo2625** [comment]
hey @sp-ytdl-core try the changes I added and see if it works. #2

**Comment by Natemo2625** [comment]
@sp-ytdl-core pull changes and try again

**Comment by koreanpanda345** [comment]
I suggest looking at the rewritten version, which can be found at https://github.com/koreanpanda345/Pokemon_Bot_Rewrite. You can of course help make it @Natemo6348 , and @sp-ytdl-core if you want to.

**Comment by Natemo2625** [comment]
Ok sure I can help, won't be able to as much right now, but I can still help some
